# This is a basic workflow to help you get started with Actions

name: codecrafters.io-testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1.2.0
        with:
          python-version: 3.6
      - name: remove existing git dir
        run: rm -rf .git
      - name: test git dir structure
        run: ./your_git.sh init && ./tests/test-dir.sh
      - name: test git cat-file
        run: ./tests/test-cat.sh
      - name: test git hash-object
        run: ./tests/test-hash.sh
      - name: test git ls-tree
        run: ./tests/test-ls-tree.sh
